spring:
  kafka:
    bootstrap-servers: localhost:9092
    key-serializer: org.springframework.kafka.support.serializer.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.StringSerializer
  producer:
    retries: 3
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

kafka:
  bootstrap-servers: localhost:9092
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
